apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-python-app
  name: my-python-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-python-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-python-app
    spec:
      containers:
      - image: {{ .Values.image.repository }}
        env:
        - name: MY_ENV_VAR
          value: "something cool"
        name: my-python-app
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
status: {}
