apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  params:
    - name: git-clone-url
      description: The URL of the Git repository to clone
      type: string
  steps:
    - name: git-clone-step
      image: alpine/git
      script: |
        git clone $(params.git-clone-url)

